---
title: "Simulation Study: CLT"
author: "Alice"
date: "12/5/2019"
output: html_document
---
---
title: "R Notebook"
output: html_notebook
---

### purpose of this study

In this simulation study, we are going to compare the sampling
distribution of the mean generated by simulation to the sampling
distribution implied by the central limit theorem. We will compare the
distributions graphically in QQ-plots.

### Underline distribution
The underlying distribution will be the Skew-Normal distribution.
The Skew-Normal distribution has three parameters: location, scale, and slant. When the slant parameter is 0, the distribution reverts to the normal
distribution. As the slant parameter increases, the distribution becomes
increasingly skewed.

### Experiment design
We will set the location and scale to 0 and 1, respectively, for all simulation
settings. This will be a 4 × 4 factorial experiment. The first factor will be the
sample size, with N = 5, 10, 20, and 40. The second factor will be the
degree of skewness in the underlying distribution.  In this simulation, slant will be set to 0, 2, 10,100.

The output of each combination of factors will be a QQ-plot. Generate a sampling distribution of 5000 draws from both the CLT approximation and the simulation approximation. When analyzing data, the parameters for the mean and variance (in the case of the CLT shortcut) or the parameters for the distribution (in the case of MLE, MM, etc) are replaced with sample estimates. (This is often called the plug-in approach.) For the purposes of this simulation, treat the mean and variance as known values and use the actual population parameters and the population mean and variance instead of sample estimates.

```{r}
require(magrittr)
require(sn)

# Parameters that do not change
R <- 5000; location <- 0; scale <- 1
# Parameters that change
one_sim <-function(N,slant){
  # Quantites to calculate/generate
  delta <- slant/(sqrt(1+slant^2))
  pop_mean <- location+scale*delta*(sqrt(2/pi))
  pop_sd <- sqrt(scale^2*(1-(2*delta^2)/pi))
  random.skew <- array(rsn(R*N, xi = location, omega = scale, alpha = slant), dim = c(R,N))
  sample_dist_sim <- apply(random.skew, 1, mean)
  sample_dist_sim
}
one_clt <-function(N,slant){
  delta <- slant/(sqrt(1+slant^2))
  pop_mean <- location+scale*delta*(sqrt(2/pi))
  pop_sd <- sqrt(scale^2*(1-(2*delta^2)/pi))
  Z <- rnorm(R)
  sample_dist_clt <- Z*(pop_sd/sqrt(N)) + pop_mean
}
# QQ plot
par(mfrow=c(4,5))
par(mar=c(0.5, 4.5, 1, 0.5))
plot(seq(-4, 4, length=100),dsn(seq(-4, 4, length=100),0,1,0),type='l',main='Distribution',ylab='slant=0')
qqplot(one_sim(5,0), one_clt(5,0), asp = 1,main='N=5')
abline(0,1)
qqplot(one_sim(10,0), one_clt(10,0), asp = 1,main='N=10')
abline(0,1)
qqplot(one_sim(20,0), one_clt(20,0), asp = 1,main='N=20')
abline(0,1)
qqplot(one_sim(40,0), one_clt(40,0), asp = 1,main='N=40')
abline(0,1)
plot(seq(-4, 4, length=100),dsn(seq(-4, 4, length=100),0,1,2),type='l',ylab='slant=2')
qqplot(one_sim(5,2), one_clt(5,2), asp = 1)
abline(0,1)
qqplot(one_sim(10,2), one_clt(10,2), asp = 1)
abline(0,1)
qqplot(one_sim(20,2), one_clt(20,2), asp = 1)
abline(0,1)
qqplot(one_sim(40,2), one_clt(40,2), asp = 1)
abline(0,1)
plot(seq(-4, 4, length=100),dsn(seq(-4, 4, length=100),0,1,10),type='l',ylab='slant=10')
qqplot(one_sim(5,10), one_clt(5,10), asp = 1)
abline(0,1)
qqplot(one_sim(10,10), one_clt(10,10), asp = 1)
abline(0,1)
qqplot(one_sim(20,10), one_clt(20,10), asp = 1)
abline(0,1)
qqplot(one_sim(40,10), one_clt(40,10), asp = 1)
abline(0,1)
plot(seq(-4, 4, length=100),dsn(seq(-4, 4, length=100),0,1,100),type='l',ylab='slant=100')
qqplot(one_sim(5,100), one_clt(5,100), asp = 1)
abline(0,1)
qqplot(one_sim(10,100), one_clt(10,100), asp = 1)
abline(0,1)
qqplot(one_sim(20,100), one_clt(20,100), asp = 1)
abline(0,1)
qqplot(one_sim(40,100), one_clt(40,100), asp = 1)
abline(0,1)
```

As we can see from the QQ-plots, when N changes, the results from simulation and central limit theorem are very similar. From QQ-plots, there are not much difference.